################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../dsp/Source/FilteringFunctions/FilteringFunctionsF16.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../dsp/Source/FilteringFunctions/arm_conv_f32.c \
../dsp/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../dsp/Source/FilteringFunctions/arm_conv_fast_q15.c \
../dsp/Source/FilteringFunctions/arm_conv_fast_q31.c \
../dsp/Source/FilteringFunctions/arm_conv_opt_q15.c \
../dsp/Source/FilteringFunctions/arm_conv_opt_q7.c \
../dsp/Source/FilteringFunctions/arm_conv_partial_f32.c \
../dsp/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../dsp/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../dsp/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../dsp/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../dsp/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../dsp/Source/FilteringFunctions/arm_conv_partial_q15.c \
../dsp/Source/FilteringFunctions/arm_conv_partial_q31.c \
../dsp/Source/FilteringFunctions/arm_conv_partial_q7.c \
../dsp/Source/FilteringFunctions/arm_conv_q15.c \
../dsp/Source/FilteringFunctions/arm_conv_q31.c \
../dsp/Source/FilteringFunctions/arm_conv_q7.c \
../dsp/Source/FilteringFunctions/arm_correlate_f16.c \
../dsp/Source/FilteringFunctions/arm_correlate_f32.c \
../dsp/Source/FilteringFunctions/arm_correlate_f64.c \
../dsp/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../dsp/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../dsp/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../dsp/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../dsp/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../dsp/Source/FilteringFunctions/arm_correlate_q15.c \
../dsp/Source/FilteringFunctions/arm_correlate_q31.c \
../dsp/Source/FilteringFunctions/arm_correlate_q7.c \
../dsp/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_f16.c \
../dsp/Source/FilteringFunctions/arm_fir_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_f64.c \
../dsp/Source/FilteringFunctions/arm_fir_fast_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_fast_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_init_f16.c \
../dsp/Source/FilteringFunctions/arm_fir_init_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_init_f64.c \
../dsp/Source/FilteringFunctions/arm_fir_init_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_init_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_init_q7.c \
../dsp/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_q7.c \
../dsp/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../dsp/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../dsp/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../dsp/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../dsp/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../dsp/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../dsp/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../dsp/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../dsp/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../dsp/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../dsp/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../dsp/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../dsp/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../dsp/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../dsp/Source/FilteringFunctions/arm_lms_f32.c \
../dsp/Source/FilteringFunctions/arm_lms_init_f32.c \
../dsp/Source/FilteringFunctions/arm_lms_init_q15.c \
../dsp/Source/FilteringFunctions/arm_lms_init_q31.c \
../dsp/Source/FilteringFunctions/arm_lms_norm_f32.c \
../dsp/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../dsp/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../dsp/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../dsp/Source/FilteringFunctions/arm_lms_norm_q15.c \
../dsp/Source/FilteringFunctions/arm_lms_norm_q31.c \
../dsp/Source/FilteringFunctions/arm_lms_q15.c \
../dsp/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./dsp/Source/FilteringFunctions/FilteringFunctionsF16.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./dsp/Source/FilteringFunctions/arm_conv_f32.o \
./dsp/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./dsp/Source/FilteringFunctions/arm_conv_fast_q15.o \
./dsp/Source/FilteringFunctions/arm_conv_fast_q31.o \
./dsp/Source/FilteringFunctions/arm_conv_opt_q15.o \
./dsp/Source/FilteringFunctions/arm_conv_opt_q7.o \
./dsp/Source/FilteringFunctions/arm_conv_partial_f32.o \
./dsp/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./dsp/Source/FilteringFunctions/arm_conv_partial_q15.o \
./dsp/Source/FilteringFunctions/arm_conv_partial_q31.o \
./dsp/Source/FilteringFunctions/arm_conv_partial_q7.o \
./dsp/Source/FilteringFunctions/arm_conv_q15.o \
./dsp/Source/FilteringFunctions/arm_conv_q31.o \
./dsp/Source/FilteringFunctions/arm_conv_q7.o \
./dsp/Source/FilteringFunctions/arm_correlate_f16.o \
./dsp/Source/FilteringFunctions/arm_correlate_f32.o \
./dsp/Source/FilteringFunctions/arm_correlate_f64.o \
./dsp/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./dsp/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./dsp/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./dsp/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./dsp/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./dsp/Source/FilteringFunctions/arm_correlate_q15.o \
./dsp/Source/FilteringFunctions/arm_correlate_q31.o \
./dsp/Source/FilteringFunctions/arm_correlate_q7.o \
./dsp/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_f16.o \
./dsp/Source/FilteringFunctions/arm_fir_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_f64.o \
./dsp/Source/FilteringFunctions/arm_fir_fast_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_fast_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_init_f16.o \
./dsp/Source/FilteringFunctions/arm_fir_init_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_init_f64.o \
./dsp/Source/FilteringFunctions/arm_fir_init_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_init_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_init_q7.o \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_q7.o \
./dsp/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./dsp/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./dsp/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./dsp/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./dsp/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./dsp/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./dsp/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./dsp/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./dsp/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./dsp/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./dsp/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./dsp/Source/FilteringFunctions/arm_lms_f32.o \
./dsp/Source/FilteringFunctions/arm_lms_init_f32.o \
./dsp/Source/FilteringFunctions/arm_lms_init_q15.o \
./dsp/Source/FilteringFunctions/arm_lms_init_q31.o \
./dsp/Source/FilteringFunctions/arm_lms_norm_f32.o \
./dsp/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./dsp/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./dsp/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./dsp/Source/FilteringFunctions/arm_lms_norm_q15.o \
./dsp/Source/FilteringFunctions/arm_lms_norm_q31.o \
./dsp/Source/FilteringFunctions/arm_lms_q15.o \
./dsp/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./dsp/Source/FilteringFunctions/FilteringFunctionsF16.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./dsp/Source/FilteringFunctions/arm_conv_f32.d \
./dsp/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./dsp/Source/FilteringFunctions/arm_conv_fast_q15.d \
./dsp/Source/FilteringFunctions/arm_conv_fast_q31.d \
./dsp/Source/FilteringFunctions/arm_conv_opt_q15.d \
./dsp/Source/FilteringFunctions/arm_conv_opt_q7.d \
./dsp/Source/FilteringFunctions/arm_conv_partial_f32.d \
./dsp/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./dsp/Source/FilteringFunctions/arm_conv_partial_q15.d \
./dsp/Source/FilteringFunctions/arm_conv_partial_q31.d \
./dsp/Source/FilteringFunctions/arm_conv_partial_q7.d \
./dsp/Source/FilteringFunctions/arm_conv_q15.d \
./dsp/Source/FilteringFunctions/arm_conv_q31.d \
./dsp/Source/FilteringFunctions/arm_conv_q7.d \
./dsp/Source/FilteringFunctions/arm_correlate_f16.d \
./dsp/Source/FilteringFunctions/arm_correlate_f32.d \
./dsp/Source/FilteringFunctions/arm_correlate_f64.d \
./dsp/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./dsp/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./dsp/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./dsp/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./dsp/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./dsp/Source/FilteringFunctions/arm_correlate_q15.d \
./dsp/Source/FilteringFunctions/arm_correlate_q31.d \
./dsp/Source/FilteringFunctions/arm_correlate_q7.d \
./dsp/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_f16.d \
./dsp/Source/FilteringFunctions/arm_fir_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_f64.d \
./dsp/Source/FilteringFunctions/arm_fir_fast_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_fast_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_init_f16.d \
./dsp/Source/FilteringFunctions/arm_fir_init_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_init_f64.d \
./dsp/Source/FilteringFunctions/arm_fir_init_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_init_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_init_q7.d \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_q7.d \
./dsp/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./dsp/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./dsp/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./dsp/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./dsp/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./dsp/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./dsp/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./dsp/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./dsp/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./dsp/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./dsp/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./dsp/Source/FilteringFunctions/arm_lms_f32.d \
./dsp/Source/FilteringFunctions/arm_lms_init_f32.d \
./dsp/Source/FilteringFunctions/arm_lms_init_q15.d \
./dsp/Source/FilteringFunctions/arm_lms_init_q31.d \
./dsp/Source/FilteringFunctions/arm_lms_norm_f32.d \
./dsp/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./dsp/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./dsp/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./dsp/Source/FilteringFunctions/arm_lms_norm_q15.d \
./dsp/Source/FilteringFunctions/arm_lms_norm_q31.d \
./dsp/Source/FilteringFunctions/arm_lms_q15.d \
./dsp/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
dsp/Source/FilteringFunctions/%.o dsp/Source/FilteringFunctions/%.su: ../dsp/Source/FilteringFunctions/%.c dsp/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F411xE -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/lenovo/Downloads/Leb4/Leb4/dsp/ComputeLibrary" -I"C:/Users/lenovo/Downloads/Leb4/Leb4/dsp/Include" -I"C:/Users/lenovo/Downloads/Leb4/Leb4/dsp/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-dsp-2f-Source-2f-FilteringFunctions

clean-dsp-2f-Source-2f-FilteringFunctions:
	-$(RM) ./dsp/Source/FilteringFunctions/FilteringFunctionsF16.d ./dsp/Source/FilteringFunctions/FilteringFunctionsF16.o ./dsp/Source/FilteringFunctions/FilteringFunctionsF16.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./dsp/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./dsp/Source/FilteringFunctions/arm_conv_f32.d ./dsp/Source/FilteringFunctions/arm_conv_f32.o ./dsp/Source/FilteringFunctions/arm_conv_f32.su ./dsp/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./dsp/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./dsp/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./dsp/Source/FilteringFunctions/arm_conv_fast_q15.d ./dsp/Source/FilteringFunctions/arm_conv_fast_q15.o ./dsp/Source/FilteringFunctions/arm_conv_fast_q15.su ./dsp/Source/FilteringFunctions/arm_conv_fast_q31.d ./dsp/Source/FilteringFunctions/arm_conv_fast_q31.o ./dsp/Source/FilteringFunctions/arm_conv_fast_q31.su ./dsp/Source/FilteringFunctions/arm_conv_opt_q15.d ./dsp/Source/FilteringFunctions/arm_conv_opt_q15.o ./dsp/Source/FilteringFunctions/arm_conv_opt_q15.su ./dsp/Source/FilteringFunctions/arm_conv_opt_q7.d ./dsp/Source/FilteringFunctions/arm_conv_opt_q7.o ./dsp/Source/FilteringFunctions/arm_conv_opt_q7.su ./dsp/Source/FilteringFunctions/arm_conv_partial_f32.d ./dsp/Source/FilteringFunctions/arm_conv_partial_f32.o ./dsp/Source/FilteringFunctions/arm_conv_partial_f32.su ./dsp/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./dsp/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./dsp/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q15.o
	-$(RM) ./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./dsp/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./dsp/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./dsp/Source/FilteringFunctions/arm_conv_partial_q15.d ./dsp/Source/FilteringFunctions/arm_conv_partial_q15.o ./dsp/Source/FilteringFunctions/arm_conv_partial_q15.su ./dsp/Source/FilteringFunctions/arm_conv_partial_q31.d ./dsp/Source/FilteringFunctions/arm_conv_partial_q31.o ./dsp/Source/FilteringFunctions/arm_conv_partial_q31.su ./dsp/Source/FilteringFunctions/arm_conv_partial_q7.d ./dsp/Source/FilteringFunctions/arm_conv_partial_q7.o ./dsp/Source/FilteringFunctions/arm_conv_partial_q7.su ./dsp/Source/FilteringFunctions/arm_conv_q15.d ./dsp/Source/FilteringFunctions/arm_conv_q15.o ./dsp/Source/FilteringFunctions/arm_conv_q15.su ./dsp/Source/FilteringFunctions/arm_conv_q31.d ./dsp/Source/FilteringFunctions/arm_conv_q31.o ./dsp/Source/FilteringFunctions/arm_conv_q31.su ./dsp/Source/FilteringFunctions/arm_conv_q7.d ./dsp/Source/FilteringFunctions/arm_conv_q7.o ./dsp/Source/FilteringFunctions/arm_conv_q7.su ./dsp/Source/FilteringFunctions/arm_correlate_f16.d ./dsp/Source/FilteringFunctions/arm_correlate_f16.o ./dsp/Source/FilteringFunctions/arm_correlate_f16.su ./dsp/Source/FilteringFunctions/arm_correlate_f32.d ./dsp/Source/FilteringFunctions/arm_correlate_f32.o ./dsp/Source/FilteringFunctions/arm_correlate_f32.su ./dsp/Source/FilteringFunctions/arm_correlate_f64.d ./dsp/Source/FilteringFunctions/arm_correlate_f64.o ./dsp/Source/FilteringFunctions/arm_correlate_f64.su ./dsp/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./dsp/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./dsp/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./dsp/Source/FilteringFunctions/arm_correlate_fast_q15.d ./dsp/Source/FilteringFunctions/arm_correlate_fast_q15.o ./dsp/Source/FilteringFunctions/arm_correlate_fast_q15.su ./dsp/Source/FilteringFunctions/arm_correlate_fast_q31.d ./dsp/Source/FilteringFunctions/arm_correlate_fast_q31.o ./dsp/Source/FilteringFunctions/arm_correlate_fast_q31.su ./dsp/Source/FilteringFunctions/arm_correlate_opt_q15.d ./dsp/Source/FilteringFunctions/arm_correlate_opt_q15.o ./dsp/Source/FilteringFunctions/arm_correlate_opt_q15.su ./dsp/Source/FilteringFunctions/arm_correlate_opt_q7.d ./dsp/Source/FilteringFunctions/arm_correlate_opt_q7.o ./dsp/Source/FilteringFunctions/arm_correlate_opt_q7.su ./dsp/Source/FilteringFunctions/arm_correlate_q15.d ./dsp/Source/FilteringFunctions/arm_correlate_q15.o ./dsp/Source/FilteringFunctions/arm_correlate_q15.su ./dsp/Source/FilteringFunctions/arm_correlate_q31.d ./dsp/Source/FilteringFunctions/arm_correlate_q31.o ./dsp/Source/FilteringFunctions/arm_correlate_q31.su ./dsp/Source/FilteringFunctions/arm_correlate_q7.d ./dsp/Source/FilteringFunctions/arm_correlate_q7.o ./dsp/Source/FilteringFunctions/arm_correlate_q7.su ./dsp/Source/FilteringFunctions/arm_fir_decimate_f32.d ./dsp/Source/FilteringFunctions/arm_fir_decimate_f32.o ./dsp/Source/FilteringFunctions/arm_fir_decimate_f32.su ./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./dsp/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./dsp/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./dsp/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./dsp/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./dsp/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./dsp/Source/FilteringFunctions/arm_fir_decimate_q15.d ./dsp/Source/FilteringFunctions/arm_fir_decimate_q15.o ./dsp/Source/FilteringFunctions/arm_fir_decimate_q15.su ./dsp/Source/FilteringFunctions/arm_fir_decimate_q31.d ./dsp/Source/FilteringFunctions/arm_fir_decimate_q31.o ./dsp/Source/FilteringFunctions/arm_fir_decimate_q31.su ./dsp/Source/FilteringFunctions/arm_fir_f16.d ./dsp/Source/FilteringFunctions/arm_fir_f16.o ./dsp/Source/FilteringFunctions/arm_fir_f16.su ./dsp/Source/FilteringFunctions/arm_fir_f32.d ./dsp/Source/FilteringFunctions/arm_fir_f32.o ./dsp/Source/FilteringFunctions/arm_fir_f32.su ./dsp/Source/FilteringFunctions/arm_fir_f64.d ./dsp/Source/FilteringFunctions/arm_fir_f64.o ./dsp/Source/FilteringFunctions/arm_fir_f64.su ./dsp/Source/FilteringFunctions/arm_fir_fast_q15.d ./dsp/Source/FilteringFunctions/arm_fir_fast_q15.o ./dsp/Source/FilteringFunctions/arm_fir_fast_q15.su ./dsp/Source/FilteringFunctions/arm_fir_fast_q31.d ./dsp/Source/FilteringFunctions/arm_fir_fast_q31.o ./dsp/Source/FilteringFunctions/arm_fir_fast_q31.su ./dsp/Source/FilteringFunctions/arm_fir_init_f16.d ./dsp/Source/FilteringFunctions/arm_fir_init_f16.o ./dsp/Source/FilteringFunctions/arm_fir_init_f16.su ./dsp/Source/FilteringFunctions/arm_fir_init_f32.d ./dsp/Source/FilteringFunctions/arm_fir_init_f32.o ./dsp/Source/FilteringFunctions/arm_fir_init_f32.su ./dsp/Source/FilteringFunctions/arm_fir_init_f64.d ./dsp/Source/FilteringFunctions/arm_fir_init_f64.o ./dsp/Source/FilteringFunctions/arm_fir_init_f64.su ./dsp/Source/FilteringFunctions/arm_fir_init_q15.d
	-$(RM) ./dsp/Source/FilteringFunctions/arm_fir_init_q15.o ./dsp/Source/FilteringFunctions/arm_fir_init_q15.su ./dsp/Source/FilteringFunctions/arm_fir_init_q31.d ./dsp/Source/FilteringFunctions/arm_fir_init_q31.o ./dsp/Source/FilteringFunctions/arm_fir_init_q31.su ./dsp/Source/FilteringFunctions/arm_fir_init_q7.d ./dsp/Source/FilteringFunctions/arm_fir_init_q7.o ./dsp/Source/FilteringFunctions/arm_fir_init_q7.su ./dsp/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./dsp/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./dsp/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./dsp/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./dsp/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./dsp/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./dsp/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./dsp/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./dsp/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./dsp/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./dsp/Source/FilteringFunctions/arm_fir_lattice_f32.d ./dsp/Source/FilteringFunctions/arm_fir_lattice_f32.o ./dsp/Source/FilteringFunctions/arm_fir_lattice_f32.su ./dsp/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./dsp/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./dsp/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./dsp/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./dsp/Source/FilteringFunctions/arm_fir_lattice_q15.d ./dsp/Source/FilteringFunctions/arm_fir_lattice_q15.o ./dsp/Source/FilteringFunctions/arm_fir_lattice_q15.su ./dsp/Source/FilteringFunctions/arm_fir_lattice_q31.d ./dsp/Source/FilteringFunctions/arm_fir_lattice_q31.o ./dsp/Source/FilteringFunctions/arm_fir_lattice_q31.su ./dsp/Source/FilteringFunctions/arm_fir_q15.d ./dsp/Source/FilteringFunctions/arm_fir_q15.o ./dsp/Source/FilteringFunctions/arm_fir_q15.su ./dsp/Source/FilteringFunctions/arm_fir_q31.d ./dsp/Source/FilteringFunctions/arm_fir_q31.o ./dsp/Source/FilteringFunctions/arm_fir_q31.su ./dsp/Source/FilteringFunctions/arm_fir_q7.d ./dsp/Source/FilteringFunctions/arm_fir_q7.o ./dsp/Source/FilteringFunctions/arm_fir_q7.su ./dsp/Source/FilteringFunctions/arm_fir_sparse_f32.d ./dsp/Source/FilteringFunctions/arm_fir_sparse_f32.o ./dsp/Source/FilteringFunctions/arm_fir_sparse_f32.su ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./dsp/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./dsp/Source/FilteringFunctions/arm_fir_sparse_q15.d ./dsp/Source/FilteringFunctions/arm_fir_sparse_q15.o ./dsp/Source/FilteringFunctions/arm_fir_sparse_q15.su ./dsp/Source/FilteringFunctions/arm_fir_sparse_q31.d ./dsp/Source/FilteringFunctions/arm_fir_sparse_q31.o ./dsp/Source/FilteringFunctions/arm_fir_sparse_q31.su ./dsp/Source/FilteringFunctions/arm_fir_sparse_q7.d ./dsp/Source/FilteringFunctions/arm_fir_sparse_q7.o ./dsp/Source/FilteringFunctions/arm_fir_sparse_q7.su ./dsp/Source/FilteringFunctions/arm_iir_lattice_f32.d ./dsp/Source/FilteringFunctions/arm_iir_lattice_f32.o ./dsp/Source/FilteringFunctions/arm_iir_lattice_f32.su ./dsp/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./dsp/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./dsp/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./dsp/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./dsp/Source/FilteringFunctions/arm_iir_lattice_q15.d ./dsp/Source/FilteringFunctions/arm_iir_lattice_q15.o ./dsp/Source/FilteringFunctions/arm_iir_lattice_q15.su ./dsp/Source/FilteringFunctions/arm_iir_lattice_q31.d ./dsp/Source/FilteringFunctions/arm_iir_lattice_q31.o ./dsp/Source/FilteringFunctions/arm_iir_lattice_q31.su ./dsp/Source/FilteringFunctions/arm_levinson_durbin_f16.d ./dsp/Source/FilteringFunctions/arm_levinson_durbin_f16.o ./dsp/Source/FilteringFunctions/arm_levinson_durbin_f16.su ./dsp/Source/FilteringFunctions/arm_levinson_durbin_f32.d ./dsp/Source/FilteringFunctions/arm_levinson_durbin_f32.o ./dsp/Source/FilteringFunctions/arm_levinson_durbin_f32.su ./dsp/Source/FilteringFunctions/arm_levinson_durbin_q31.d ./dsp/Source/FilteringFunctions/arm_levinson_durbin_q31.o ./dsp/Source/FilteringFunctions/arm_levinson_durbin_q31.su ./dsp/Source/FilteringFunctions/arm_lms_f32.d ./dsp/Source/FilteringFunctions/arm_lms_f32.o ./dsp/Source/FilteringFunctions/arm_lms_f32.su
	-$(RM) ./dsp/Source/FilteringFunctions/arm_lms_init_f32.d ./dsp/Source/FilteringFunctions/arm_lms_init_f32.o ./dsp/Source/FilteringFunctions/arm_lms_init_f32.su ./dsp/Source/FilteringFunctions/arm_lms_init_q15.d ./dsp/Source/FilteringFunctions/arm_lms_init_q15.o ./dsp/Source/FilteringFunctions/arm_lms_init_q15.su ./dsp/Source/FilteringFunctions/arm_lms_init_q31.d ./dsp/Source/FilteringFunctions/arm_lms_init_q31.o ./dsp/Source/FilteringFunctions/arm_lms_init_q31.su ./dsp/Source/FilteringFunctions/arm_lms_norm_f32.d ./dsp/Source/FilteringFunctions/arm_lms_norm_f32.o ./dsp/Source/FilteringFunctions/arm_lms_norm_f32.su ./dsp/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./dsp/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./dsp/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./dsp/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./dsp/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./dsp/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./dsp/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./dsp/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./dsp/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./dsp/Source/FilteringFunctions/arm_lms_norm_q15.d ./dsp/Source/FilteringFunctions/arm_lms_norm_q15.o ./dsp/Source/FilteringFunctions/arm_lms_norm_q15.su ./dsp/Source/FilteringFunctions/arm_lms_norm_q31.d ./dsp/Source/FilteringFunctions/arm_lms_norm_q31.o ./dsp/Source/FilteringFunctions/arm_lms_norm_q31.su ./dsp/Source/FilteringFunctions/arm_lms_q15.d ./dsp/Source/FilteringFunctions/arm_lms_q15.o ./dsp/Source/FilteringFunctions/arm_lms_q15.su ./dsp/Source/FilteringFunctions/arm_lms_q31.d ./dsp/Source/FilteringFunctions/arm_lms_q31.o ./dsp/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-dsp-2f-Source-2f-FilteringFunctions

